theme = "deluxe_dark"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
# show open buffers: bufferline = "multiple"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"
center = ["workspace-diagnostics"]

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.soft-wrap]
enable = true

[keys.normal]
j = "move_char_left"
k = "move_line_down"
l = "move_line_up"
";" = "move_char_right"
# Move ten lines up or down on shifted movement key
K = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down", 
     "move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"] 

L = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up", 
     "move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"] 

# Mark til end of line / start of line
J = ["extend_to_line_start"]
":" = ["extend_to_line_end"]

i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

# Search for word under cursor
"e" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"E" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

"C-j" = "join_selections"
"C-J" = "join_selections_space"

# vim-like motions without expanding selection
# W = ["move_next_word_start", "collapse_selection"]
# B = ["move_prev_word_start", "collapse_selection"]

# extending movement
"C-w" = "extend_next_word_start"
"C-W" = "extend_next_long_word_start"
"C-b" = "extend_prev_word_start"
"C-B" = "extend_prev_long_word_start"
"C-h" = "extend_to_first_nonwhitespace"
"C-H" = "extend_to_line_start"
"C-l" = "extend_to_line_end"
"C-L" = "extend_to_line_end_newline"
# "C-t" = "extend_till_next_char"
"C-T" = "extend_till_prev_char"
"C-f" = "extend_next_char"
"C-F" = "extend_prev_char"

"<" = "shrink_selection"
">" = "expand_selection"

# macOS movements
"A-left" = "move_prev_word_start"
"A-right" = "move_next_word_end"
"S-A-left" = "extend_prev_word_start"
"S-A-right" = "extend_next_word_end"
"S-up" = "extend_line_up"
"S-down" = "extend_line_down"
"C-S-down" = "copy_selection_on_next_line"
"C-S-up" = "copy_selection_on_prev_line"

# macOS-like deletions
"backspace" = "delete_char_backward"
"C-backspace" = "delete_char_forward"
"A-backspace" = "delete_word_backward"
"C-A-backspace" = "delete_word_forward"
"S-backspace" = "delete_selection"

# Tab-indentation
"tab" = "indent"
"S-tab" = "unindent"

# Insert mode toggle
"C-i" = "insert_mode"

# vim-impaired style movement for navigating buffers
"[" = { b = "goto_previous_buffer", s = "select_prev_sibling" }
"]" = { b = "goto_next_buffer", s = "select_next_sibling" }

# Use clipboard instead of registers
y = ["yank_main_selection_to_clipboard", "collapse_selection"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
"C-p" = "replace_selections_with_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"

# Other remaps
z = "undo"
Z = "redo"

u = "switch_to_lowercase"
U = "switch_to_uppercase"
"C-u" = "switch_case"

C = "toggle_comments"
"C-c" = "copy_selection_on_next_line"
"C-C" = "copy_selection_on_prev_line"

"'" = "select_regex"

# "-s" = ":write-all"
# Jump Mode keys
s = "goto_word"

G = "goto_file_end"

# TODO: Remap "Select Regex" keys

[keys.normal.space.z]
j = "align_view_top"
k = "scroll_down"
l = "scroll_up"
";" = "align_view_bottom"
c = "align_view_center"
z = "align_view_center"

[keys.normal.g]
j = "goto_first_nonwhitespace"
k = "goto_file_start"
";" = "goto_line_end"

I = "goto_implementation"

[keys.normal.space]
"," = "last_picker"
space = "file_picker"
p = "paste_after"
P = "paste_before"

[keys.normal.space.w]
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_up"
";" = "jump_view_right"

[keys.normal.A-w]
j = "jump_view_left"
k = "jump_view_down"
E = "join_selections"
"A-E" = "join_selections_space"

i = "jump_view_up"
I = "keep_selections"
"A-I" = "remove_selections"

o = "jump_view_right"

[keys.normal.D]
# vim-like delete mode
w = "delete_word_forward"
W = ["move_next_long_word_start", "delete_selection", "collapse_selection", "normal_mode"]
b = "delete_word_backward"
B = ["move_prev_word_start", "delete_selection", "collapse_selection", "normal_mode"]
n = "kill_to_line_start"
o = "kill_to_line_end"
x = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
d = "delete_selection_noyank"
y = "delete_selection"

[keys.normal.Y]
# vim-like yanking
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
b = ["move_prev_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
B = ["move_prev_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
x = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
y = "yank_main_selection_to_clipboard"
d = "delete_selection"

[keys.insert]
# Normal mode toggle
"C-n" = "normal_mode" 

# macOS-like deletions
"C-backspace" = "delete_char_forward"
"A-backspace" = "delete_word_backward"
"C-A-backspace" = "delete_word_forward"

[keys.select]
# Colemak movements and remap of conflicted keys
j = "extend_char_left"
k = "extend_line_down"
l = "extend_line_up"
";" = "extend_char_right"
J = "extend_to_first_nonwhitespace"
K = "no_op"
L = "no_op"
":" = "extend_to_line_end"


