[[language]]
name = "verilog"
scope = "source.verilog"
file-types = ["vh", "sv", "svh"]

[[language]]
name = "atom"
scope = "source.atom"
file-types = ["atom"]
auto-format = true
comment-tokens = "//"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "blitz"
scope = "source.blitz"
file-types = ["blitz"]
auto-format = true
comment-tokens = "//"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "copilot"]

[[language]]
name = "galvan"
scope = "source.galvan"
file-types = ["galvan"]
comment-tokens = "//"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "type"
scope = "source.type"
file-types = ["ty", "type"]
comment-tokens = "//"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "wtf"
scope = "source.wtf"
file-types = ["wtf"]
comment-tokens = "//"
indent = { tab-width = 4, unit = "    "}
language-servers = ["wtf-lsp"]

[[language]]
name = "goto"
scope = "source.goto"
file-types = ["goto"]
comment-tokens = "//"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "moonbit"
scope = ""
file-types = ["mbt"]
comment-tokens = "//"
indent = { tab-width = 4, unit = "    "}
language-servers = ["moonbit-lsp"]

[language-server.copilot]
command = "copilot-node-server"

[language-server.moonbit-lsp]
command = "moonbit-lsp"

[language-server.wtf-lsp]
command = "wtf-lsp"

[[grammar]]
name = "blitz"
source = { git = "https://github.com/antoniusnaumann/tree-sitter-blitz", rev = "71019175a8fb6ba7dff1e1395bea035278a6f620" }

[[grammar]]
name = "galvan"
source = { git = "https://github.com/antoniusnaumann/tree-sitter-galvan", rev = "824826b23fa68561489e9b63fbfbb4ce6dd258c7" }

[[grammar]]
name = "atom"
source = { git = "https://github.com/antoniusnaumann/tree-sitter-atom", rev = "22afc64a9a742d2ee8a46dc404c3ac5e1df5e07d" }

[[grammar]]
name = "goto"
source = { git = "https://github.com/goto-lang/tree-sitter-goto", rev = "785bacaa82546567468f48bbbd5f873d8ba49158"}

[[grammar]]
name = "type"
source = { git = "https://github.com/antoniusnaumann/tree-sitter-type", rev = "fd951ad46d771588f0512558d65b2588c84a3785" }

[[grammar]]
name = "wtf"
source = { git = "https://github.com/antoniusnaumann/tree-sitter-wtf", rev = "3696dfcaef18408f643d50e3f62d5d00f7d673b8" }

[[grammar]]
name = "moonbit"
source = { git = "https://github.com/moonbitlang/tree-sitter-moonbit", rev = "f59e7d0d88479bb74505c2bdc82474fb319de05d" }
